### ISSUE TITLE
upgrade kernel

### ISSUE THREAD

**Issue by amlopin** [kotc/ovhnas#2]
Hi,

I have been using 4.9.150-kc375 for a long time and it has been working fantastic, amazing, many thanks!!
Today I came to this github page and I realized that there is a newer version: "currently 4.9.172"

I tried to update: "sudo apt update" and "sudo apt upgrade" but it did not upgrade haha

So, how can I install the lastest kernel?

My SYS-arm server has been working as a charm since I installed your kernel. 
Thank you very much

**Comment by kotc** [comment]
since i chose universal distribution method, it's not a regular package.

1/ you can switch to ovh provided kernel by installing proper package
2/ if you prefer to use kc375 series, just run installer script again

also, i should update the description on this page whenever i compile and release new version

**Comment by amlopin** [comment]
Wow Is there a new version???  Amazing! youre a star!!!! I completely forgot ( I got short memory... hahaha ) how to run the script and the password.... I think I should go to the help channel

Thanks mate!!!

**Comment by amlopin** [comment]
Everything sorted very fast in the irc channel. Thank you so much :D
